### PR TITLE
fix: update readme links

### PR DESCRIPTION
**Pull request by mtm0183**

### CODE REVIEW

**Comment by mattgreg** [comment]
Looks great. Go ahead and push to ```main```

**Comment by mrinalwadhwa** [comment]
The website renders the README in the design folder. That is intentional, please add it back with the correct links.
https://github.com/ockam-network/website/blob/production/dependencies_repos.csv#L2

**Comment by mtm0183** [comment]
@mattgreg @mrinalwadhwa Do we want the README in both places? Or just move it to design?

**Comment by mrinalwadhwa** [comment]
Both places.
Just fix the mentions of `master` to `main` in the links and add the new proposal where missing.

**Comment by mrinalwadhwa** [comment]
@mtm0183 could you squash this into a single commit please.

**Pull request merged**
