### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zwizwa**
Fixed broken link to https://kaitai.io/

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@zwizwa awesome, thank you for fixing this.
Could you do me a quick favor and amend the commit message to say something like `OP-0004: fix broken link to kaitai`

```
git commit --amend
git push --force
```
I'll be sure to document the commit message format today and add a contribution guide.

**Comment by mattgreg** [comment]
I love this. Thanks for the PR!

**Comment by mrinalwadhwa** [comment]
@zwizwa almost there, before I can push the merge, could you add your GPG public key to https://github.com/settings/keys so Github can verify the commit.

We have "verified commits only" rule on the master branch.

**Comment by zwizwa** [comment]
Sorry I uploaded the wrong key. Both are there now.

**Pull request merged**
